### ISSUE TITLE
Feature Request: PostgreSQL?

### ISSUE THREAD

**Issue by frederikhors** [ForetagInc/Alchemy#11]
Anything planned for PostgreSQL?

**Comment by itsezc** [comment]
Currently our focus is ArangoDB exclusively, however we do plan to add support for multiple databases via a feature called BYOD (bring your own database) in the future, where a Postgres connector can be added; however, this is not something we expect to work on any time soon.

**Comment by frederikhors** [comment]
Thanks.

**Comment by joshua1** [comment]
May I ask why the choice of ArangoDB . Hoping I can learn something from the responses about ArangoDB. sorry for jumping on a closed issue
