### ISSUE TITLE
Bug: Filter available on unique relationships

### ISSUE THREAD

**Issue by KennethGomez** [ForetagInc/Alchemy#15]
### Preliminary checklist

- [X] I understand that all communication must be in English
- [X] I read the [Documentation](https://engineering.foret.ag)
- [X] I read the [Contributing guide](https://github.com/ForetagInc/.github/blob/master/CONTRIBUTING.md)
- [X] I agree to follow the [Code of Conduct](https://github.com/ForetagInc/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I searched the issues and discussions but couldn't find anything (or linked relevant results below)

### Version

dev

### Environment

N/A

### Background

Whenever you create a relationship between two entities on which one of the arms of the relationship is a **One**, for example: `ManyToOne`, `OneToMany`, `OneToOne`, the Schema generated should create on the `One` arm a single-entity returning type without any filter as it doesn't make sense to filter something that is always one.

### Current behavior

Right now the Schema generated adds filtering for both arms.

### Steps To Reproduce

1. Create one entity, example: Account
2. Create another entity, example: Role
3. Create a relationship between these entities with a relationship property on both of them: AccountRole

### Screenshot or Screencast

![image](https://user-images.githubusercontent.com/22857471/185447932-93a1ed21-36d6-4817-855e-7b02ffa8967c.png)

### Solution

Disable filtering for single-entity returning fields

### Contribution

Yes, I will work on a PR

### Keywords

graphql, relationships

**Comment by itsezc** [comment]
Bug confirmed
