### ISSUE TITLE
Feature Request: Schema (re)generation on runtime

### ISSUE THREAD

**Issue by itsezc** [ForetagInc/Alchemy#9]
### Is your proposal related to a problem?

Currently there is no way to use Alchemy before making any changes via the Meta API or by manually altering the `alchemy_collections`, this requires a complete a rebuild / rerun of the project taking up valuable development time.

### Describe the solution you'd like

We should abstract the schema generation allowing for on demand schema generation and then Alchemy should rely on Arango events to trigger a schema regeneration when changes are made to the `alchemy_collections` and other relevant collections.

### Describe alternatives you've considered

References to projects that rely on HTTP Streams from Arango:
https://github.com/baslr/arangochair
https://github.com/baslr/arangochair-serversendevents-demo

**Comment by KennethGomez** [comment]
Solved within 6630400ba4563b0a11a9424a8bed49d713a12782...b8ff6b3575e71d3591038c0ef63fa4bc23077b06
